"use client";

import {
  LucideProps,
  Moon,
  SunMedium,
  Laptop,
  User,
  LogOut,
  Settings,
  X,
  Menu,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Plus,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Loader2,
  MoreVertical,
  Search,
  Trash,
  Twitter,
  UserPlus,
  Github,
} from "lucide-react";

export type Icon = React.ElementType;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  user: User,
  settings: Settings,
  logout: LogOut,
  close: X,
  menu: Menu,
  check: Check,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  plus: Plus,
  creditCard: CreditCard,
  file: File,
  fileText: FileText,
  helpCircle: HelpCircle,
  image: Image,
  loader: Loader2,
  moreVertical: MoreVertical,
  search: Search,
  trash: Trash,
  twitter: Twitter,
  userPlus: UserPlus,
  github: Github,
  spinner: Loader2,
};